### ISSUE TITLE
Having difficulties compiling

### ISSUE THREAD

**Issue by Sailsman63** [izpack/izpack#354] opened 2015-05-27 04:12 UTC
Was not able to find a better place to put this, so here goes:

I'm not able to build current master, nor Tags 5.0.0 rc5 or 4.3.7. (not tried others)

My IDE's Maven integration (Intellij) claims that Maven can't resolve a dependency in Izpack dist > plugins > org.codehaus.izpack:izpack-maven-plugin:5.0.0-rc5-SNAPSHOT

Is this a known issue, or am I doing something wrong?

**Comment by rkrell** [comment] 2015-05-27 06:31
Hi, there is no known issue and IzPack is compiling fine for me including the unit tests. Please try to re-clone the repository from here, checkout the master branch an retry.

If you have further trouble please provide some out, logs and the JDK version you are using.

**Comment by Sailsman63** [comment] 2015-05-27 14:33
Okay, no joy there.

I'm attaching a link to my [command-line outputs, as well as all the surefire tests output](https://drive.google.com/folderview?id=0B8dhNVBeB9VTflNtMjdONFFPTEdONVpLRGJGQ3E5dGNMaGxGMVRNeENsLVlNZTFBaE5sWUk&usp=sharing), in case they are relevant.

Build basics:

Win 7 Pro 64 bit.
Oracle JDK 1.8.0_45 64 bit
Maven 3.3.3, apache compiled binary
Git 1.9.5.mysysgit.1, official git for windows installer.

Everything in this build, including git clone/checkout was done on the command line. Not a maven expert (Thanks for the impetus to get the thing installed properly!) But I suspect that the first clue is in izpack-buildlog.txt, at about line 56.

**Comment by rkrell** [comment] 2015-05-27 15:26
I see. Just some explanation at the beginning: We are still compatible to and compile with JDK 1.6. We have CI systems connected compiling additionally on Oracle 1.7 and OpenJDK 7. The Java 8 builds should of course work in future, but didn't receive the appropriate attention.

 Just a quick test on Linux (no Windows build environment available at the moment):

Using Maven 3.2.5 (which is the latest version still compiling with JDK 1.6):
export JAVA_HOME=/usr/java/jdk1.6.0_45/
mvn clean
mvn verify
--> OK

export JAVA_HOME=/usr/java/jdk1.7.0_75/
mvn clean
mvn verify
--> OK

export JAVA_HOME=/usr/java/jdk1.8.0_31/
mvn clean
mvn verify
--> TEST FAILURES (although there are concerned different tests than for your case)

Thus more or less the JDK 1.8 builds seem to be still crap.
Leaving this issue open to be done.
You can use JDK 1.7 meanwhile to get it hopefully compiled locally.

**Comment by Sailsman63** [comment] 2015-05-27 16:24
Thanks for getting back to me so quickly. I've tried using JDK 1.7.0, and got the same results in my output. Looking at some of the surefire test output, the build system _is_ seeing my 1.7 installation.

I've added a full debug (mvn -X) log to the same location as before, buildlog_extended.txt, just in case there is useful info there.

Question regarding a possible workaround: Is there a new location for a pre-compiled distribution? The old links seem to point to a part of codehaus that has been taken down.

**Comment by rkrell** [comment] 2015-05-27 16:40
Ah, I think I found it: In method com.izforge.izpack.util.xmlmerge.XmlMergeTest.testMergeFilesWithXPathTagMatcherReplace2Files(), there is a missing null check in the finally branch for the both FileChannel instances:
```java
        FileChannel inputChannel = null;
        FileChannel outputChannel = null;
        try {
            inputChannel = new FileInputStream(new File(patchTargetFileUrl.getFile())).getChannel();
            outputChannel = new FileOutputStream(targetFile).getChannel();
            outputChannel.transferFrom(inputChannel, 0, inputChannel.size());
        } finally {
            inputChannel.close();
            outputChannel.close();
        }
```
For some reason, on your OS the transferFrom method seems to null them.
I will fix this soon, you can meanwhile skip the unit tests (-DskipTests=true) or skip this dedicated one if you want.

**Comment by Sailsman63** [comment] 2015-05-27 18:18
Thanks, I now have a working build... On to fixing the installer definition I was looking at!

I'll look at fixing the bug later, and we'll see how that goes.

**Comment by rkrell** [comment] 2015-05-29 09:13
This problem should be fixed now, merged pull request #355

**Comment by Sailsman63** [comment] 2015-05-30 04:25
Just tried a fresh compile with both JDK 1.7 and 1.8. Now I am getting:

`java.io.FileNotFoundException: C:\Users\Admin\Programming%20Stuff\izpack\izpack-util\target\test-classes\com\izforge\izpack\util\xmlmerge\maps_resources_original.xml (The system cannot find the path specified)`

In the same test as before.
When I check manually, the path & file definitely exist. Which makes this even weirder.

**Comment by rkrell** [comment] 2015-05-30 06:24
How did you compile this on the command line?

2015-05-30 6:25 GMT+02:00 Sailsman63 <notifications@github.com>:

**Comment by Sailsman63** [comment] 2015-05-30 13:02
`git pull` to update source.
`git rev-parse --short HEAD` and double check against latest commit hash here on gitub (I'm newer to git, so some of this is for my own education)
`mvn clean`
`mvn verify`

repeat the maven targets after setting JAVA_HOME to my 1.7 JDK directory. Both outputs the same.
[Full Trace](https://drive.google.com/open?id=0B8dhNVBeB9VTUExYZE44UlFGWms&authuser=0)

**Comment by rkrell** [comment] 2015-05-31 00:34
Please try this again with the current master HEAD.
It seems like my last fix hasn't been correct. There has been rather bad file handling due to the space in the build directory path.

**Comment by Sailsman63** [comment] 2015-05-31 00:54
testMergeFilesWithXPathTagMatcherReplace2Files(com.izforge.izpack.util.xmlmerge.XmlMergeTest)  Time elapsed: 0 sec  <<< ERROR!
com.izforge.izpack.util.xmlmerge.ParseException: java.io.FileNotFoundException: C:\Users\Admin\Programming%20Stuff\izpack\izpack-util\target\test-classes\com\izforge\izpack\util\xmlmerge\maps_resources_patch.xml (The system cannot find the path specified)
	at com.izforge.izpack.util.xmlmerge.merge.DefaultXmlMerge.merge(DefaultXmlMerge.java:223)
	at com.izforge.izpack.util.xmlmerge.config.ConfigurableXmlMerge.merge(ConfigurableXmlMerge.java:85)
	at com.izforge.izpack.util.xmlmerge.XmlMergeTest.testMergeFilesWithXPathTagMatcherReplace2Files(XmlMergeTest.java:137)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
(.... The rest seems to be setting up the test harness ...)

Only JDK 1.8.
Windows does have... unique... directory handling.

**Comment by rkrell** [comment] 2015-05-31 08:18
OMG, it seems like I have to set up a Windows build environment...
The way of opening a file over an URI is used also in other tests, it can be expected they will also fail.
Nevertheless, no blocker for 5.0 RC5 so far.
Leaving this open so far.

**Comment by Sailsman63** [comment] 2015-05-31 13:20
Fair enough. IZPack does work for me, as long as I skip that test. I'm pretty new to maven, so have not tried yet to skip _only_ that test.

I'll have to try installing to a path that includes that directory to see if it's just the tests, or if the build has issues there as well.

**Comment by akuhtz** [comment] 2015-06-01 16:22
Hello René,
The problem is the space in the path. We had the same problem in march and the fix is the same:
In line 139 and 154 the pathSourceFileUrl.getFile() must be replaced with pathSourceFileUrl.toURI().
I'll try to prepare a PR if you're not faster :-)

**Comment by rkrell** [comment] 2015-06-01 21:03
Hurray and thanks for helping, please send a PR.
I'm currently busy with releasing.
This fix can get into the code after RC5, not so critical.

**Comment by rkrell** [comment] 2015-06-01 21:09
Andreas was fast like a hurricane.
@Sailsman63: Please check this fix from the latest master, tell us if this works for you or reopen in case of further trouble.
Thanks you all guys.

**Closed by rkrell** 2015-06-01 21:09 UTC
Labels: bug, izpack:build

**Comment by Sailsman63** [comment] 2015-06-02 13:59
Well, this issue seems to be resolved! Thanks. I have now moved on to other test failures. Shall I report them here, or open a new issue for each? New failure is in another unit, with errors not related to file io.

**Comment by rkrell** [comment] 2015-06-02 14:09
Please open a new issue, since 5.0 RC5 is already released and the previous fix got there, while further fixes go to the next snapshot.
